spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:db/h2/data.sql
  h2:
    console.enabled: true