spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/h2/schema.sql
      data-locations: classpath:db/h2/data.sql
  h2:
    console.enabled: true
